FROM postgres:16-bookworm

# Copy the entry point script into the container
COPY create_databases.sh /docker-entrypoint-initdb.d/create_databases.sh
RUN chmod +x /docker-entrypoint-initdb.d/create_databases.sh

# Install additional packages if needed
RUN apt-get update && \
    apt-get -y install postgresql-16-cron && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
