version: "3.9"

services:
  djangoapp: 
    container_name: Django
    build: .
    
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=Techleadz
      - PG_DB=Task
      - PG_PORT=5432
      - PG_HOST=db
      - PACKAGR_REPOSITORY_URL=https://api.packagr.app/nwji80I0Y
      - PACKAGR_USERNAME=testleadz0014@gmail.com
      - PACKAGR_TOKEN=029cc1441118c85dabdbacf55cad7e4bd3f5c7ed
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    build:
      context: .
      dockerfile: Dockerfile.pg_cron
    container_name: docker-posgres-cron
    command: [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr",
        "-c",
        "shared_preload_libraries=pg_cron",
        "-c",
        "cron.database_name=${POSTGRES_DB-Task}",
    ]
    environment:
      - POSTGRES_DB=Task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Techleadz
    volumes:
      - pg_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

    

volumes:
  pg_db: