"""
Django settings for gcs project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os 
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^*+=&obzaac@1&(3&7&gex=f++54o^ii2l=ijuwy%w+vfsz34('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []

ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'task',
    'debug_toolbar',
    'django_crontab',
    'rest_framework.authtoken',
    'social_django',
]

STATIC_URL = "static/"

CRONJOBS = [
    ('2-59/2 * * * *', 'task.job'),
]


MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)


ROOT_URLCONF = 'gcs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'task/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gcs.wsgi.application'

INTERNAL_IPS = [
    # Docker IP Address
    '172.17.0.1',
    # Localhost
    '127.0.0.1',
    '::1',
]


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_DRIVER','django.db.backends.postgresql'),
        'USER': os.environ.get('PG_USER','postgres'),
        'PASSWORD':os.environ.get('PG_PASSWORD','Techleadz'),
        'NAME': os.environ.get('PG_DB','Task'),
        'PORT': os.environ.get('PG_PORT','5432'), #5433
        'HOST': os.environ.get('PG_HOST','localhost'),
    },
    # 'second': {
    #     'ENGINE': os.environ.get('DB_DRIVER','django.db.backends.postgresql'),
    #     'USER': os.environ.get('PG_USER','postgres'),
    #     'PASSWORD':os.environ.get('PG_PASSWORD','Techleadz'),
    #     'NAME': os.environ.get('PG_DB','SGC'),
    #     'PORT': os.environ.get('PG_PORT','5433'),
    #     'HOST': os.environ.get('PG_HOST','localhost'),
    # }
}

# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10,
# }
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google Keys
AUTH_USER_MODEL = 'task.Users'
GOOGLE_CLIENT_ID = '709649409869-vqndc98e1iqof8q194hlu5qc5qaa8ou1.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = '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'
GOOGLE_REDIRECT_URI = 'http://localhost:8000/login/google/callback/'

#Facebook Keys
SOCIAL_AUTH_FACEBOOK_KEY = '1017525933233415'
SOCIAL_AUTH_FACEBOOK_SECRET = 'dcda69fe45ab82d5470ceac876cde579'
FACEBOOK_REDIRECT_URI = 'http://localhost:8000/facebook/callback/'


#Github Keys
GITHUB_CLIENT_ID = 'Ov23liozwXdew6vqcGk8'
GITHUB_CLIENT_SECRET = 'd2249256a605b793d1957e21925a36b92bbd6f4d'
GITHUB_REDIRECT_URI = 'http://localhost:8000/github/callback' 