# Generated by Django 5.0.3 on 2024-03-27 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgc_name', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sgc_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C')], max_length=1)),
            ],
        ),
    ]
