# Generated by Django 5.0.3 on 2024-03-29 13:57
from django.contrib.postgres.operations import CreateExtension
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('service_details', models.CharField(default='It solutions')),
            ],
        ),
        CreateExtension('pg_cron'),
    ]
