# Generated by Django 3.2.5 on 2024-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_details',
            field=models.CharField(default='It solutions', max_length=255),
        ),
    ]
