# Generated by Django 3.2.5 on 2024-07-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_services_service_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_details',
            field=models.CharField(blank=True, default='It solutions', max_length=255, null=True),
        ),
    ]
