# Generated by Django 5.0.3 on 2024-06-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', max_length=10),
        ),
    ]
